### ISSUE TITLE
Implement filters for classes in Ruby core?

### ISSUE THREAD

**Issue by tfausak** [AaronLasseigne/active_interaction#187]
There are many classes in [Ruby core](http://ruby-doc.org/core-1.9.3/) that we don't have filters for. Should we add filters for them?
- [Complex](http://ruby-doc.org/core-1.9.3/Complex.html)
- [Dir](http://ruby-doc.org/core-1.9.3/Dir.html)
- [Enumerator](http://ruby-doc.org/core-1.9.3/Enumerator.html)
- [IO](http://ruby-doc.org/core-1.9.3/IO.html)
- [Range](http://ruby-doc.org/core-1.9.3/Range.html)
- [Rational](http://ruby-doc.org/core-1.9.3/Rational.html)
- [Regexp](http://ruby-doc.org/core-1.9.3/Regexp.html)

**Comment by danbartlett** [comment]
I just started using `active_interaction` today, and the first thing I've been looking for is something like `range :date_range` to ensure a valid `Range` is passed :)

**Comment by tfausak** [comment]
ActiveInteraction doesn't have `Range` filters, but there are a couple ways to do that.

- Create two separate inputs, like `date :start_date, :end_date`. This is how I prefer to do it. 
- Use [an `Object` filter](https://github.com/orgsync/active_interaction/blob/v3.3.0/README.md#object) with `class: Range`. You'll have to add an additional validation to make sure it's a range of `Date`s.

Do either of those work for you?

**Comment by danbartlett** [comment]
Thanks for the advice @tfausak. I went with the second option—as I'd prefer to pass a singular `Range` about—and wrote a custom validator as I'll be doing a lot with date ranges:

```
class JournalView < ActiveInteraction::Base
  object :date_range, class: 'Range', default: nil
  validates_with DateRangeValidator
end
```

**Comment by casiodk** [comment]
I think something like [dry types enums](https://dry-rb.org/gems/dry-types/1.2/enum/) would be a great addition to the library!!
