### ISSUE TITLE
Is there a way to group optional attributes?

### ISSUE THREAD

**Issue by prashantham** [AaronLasseigne/active_interaction#188]
Like mutations
 optional do
    boolean :newsletter_subscribe
  end

Or i need to define each attribute with default: nil.

**Comment by tfausak** [comment]
A year and a half later, I learned about [`with_options`](http://api.rubyonrails.org/classes/Object.html#method-i-with_options). You could use that to group optional inputs.

``` rb
with_options default: nil do
  boolean :a
  boolean :b
  boolean :c
  boolean :d
end
```
