### ISSUE TITLE
Compose does not merge errors correctly when field name is missing

### ISSUE THREAD

**Issue by antulik** [AaronLasseigne/active_interaction#404]
active_interaction (3.4.0)

To reproduce:

```ruby
class A < ActiveInteraction::Base
  string :phone

  def execute
    compose(B, different_field: phone)
  end
end

class B < ActiveInteraction::Base
  string :different_field
  validates :different_field, length: { minimum: 10, maximum: 15 }

  def execute
  end
end

outcome = A.run(phone: '123')
puts outcome.errors.full_messages.join(' and ')
#=> Different field {:one=>"is too short (minimum is 1 character)", :other=>"is too short (minimum is %{count} characters)"}
```

The issue happens when nested composition doesn't have the same field as the parent.

If it's the same field, everything works fine.

**Comment by tfausak** [comment]
Thanks for reporting this bug! This is pretty annoying, but I'm not sure if it's any different than the case we warn about in the documentation: https://github.com/orgsync/active_interaction/blob/v3.4.0/README.md#errors

**Comment by antulik** [comment]
Warning that it's broken is fine, but would be good to have it fixed eventually, otherwise compose is half broken feature.

Interesting thing, while I was doing workaround for another issue. That bug accidentally was fixed as well. https://github.com/orgsync/active_interaction/issues/405#issuecomment-270517606 

Simply copying errors into new errors object and then merging as usual fixed this bug. I haven't investigated exactly why it is like that.
