### ISSUE TITLE
Add converter option to object filter

### ISSUE THREAD

**Issue by antulik** [AaronLasseigne/active_interaction#420]
I propose to add `converter` option to `object` filter. For example:

```ruby
object :table, class: OpenStruct, converter: :new 
```

It will give ability to provide custom cast logic. 

```ruby
result = interaction.run!(table: {a: 1})
result.table.a 
# => 1
result.table.class
# => OpenStruct
```

The idea and behaviour is taken from [composed_of](http://api.rubyonrails.org/classes/ActiveRecord/Aggregations/ClassMethods.html#method-i-composed_of) method in Rails: 

> :converter - A symbol specifying the name of a class method of :class_name or a Proc that is called when a new value is assigned to the value object. The converter is passed the single value that is used in the assignment and is only called if the new value is not an instance of :class_name. If :allow_nil is set to true, the converter can return nil to skip the assignment.

Note: the example above is simplified, the actual usecase is different

**Comment by AaronLasseigne** [comment]
Would it be possible for you to provide the actual usecase?

**Comment by antulik** [comment]
I thought of it when I was working with nested forms in Rails. Let's assume example

```ruby
class A < ActiveInteraction::Base
  string :a
  object :b_form, class: B 

  def execute
  end
end

class B < ActiveInteraction::Base
  string :b

  def execute
  end
end
```

```erb
<%= form_for @form do |form| %>
  <%= form.text_field :a %>
  <%= f.fields_for :b_form, f.object.b_form do |b_form| %>
    <%= b_form.text_field :b %>
  <% end %>
<% end %>
```

`fields_for` requires the field to be an active model object, so normal hash won't work.
Merging inputs from B form into A might be an option. But for our case we choose the nested form dynamically so inputs might vary.

Now after thinking about it, I understand that the usecase could be rare and is probably not worth the effort. Just thought to share the limitation I've faced.

**Comment by AaronLasseigne** [comment]
I don't think it's a bad idea but I'm not sure how much use it would get. For the moment, I'm going to close this.

**Comment by AaronLasseigne** [comment]
I've decided to reopen this. I think it could be useful in helping to easily create value objects.

**Comment by AaronLasseigne** [comment]
I'm going to do a minor release and add this.

https://github.com/AaronLasseigne/active_interaction/tree/v3.6.0#object
