### ISSUE TITLE
Object finders

### ISSUE THREAD

**Issue by antulik** [AaronLasseigne/active_interaction#422]
Let's start with the example: 

```ruby
class NotifyUser < ApplicationForm
  object :user, class: User
end

NotifyUser.run(user_id: 1)
```

The idea that `object` filters accept `_id` input if object itself is not given and user finder to get the object by id, e.g. `User.find(id)`.

That makes interactions easy to use with primitive datatypes and simplifies interaction logic as you skip boilerplate code. 

I think that feature must be opt-in so it's not ActiveRecord specific and finder could be customised. 

On the negative side that magnifies the existing problem of using primitive types and hacker can pass those fields in the form. E.g.:

```ruby
class NotifyUser < ApplicationForm
  object :user, class: User
  object :profile, class: Profile, default: -> { user.profile }
end

NotifyUser.run(params.merge(user: current_user))
```

In the example above `params` could have `profile_id` set, so profile will be set by user rather than `default` block.

Thoughts?

**Comment by AaronLasseigne** [comment]
The `object` filter is supposed to be generic so, as you point out, `find` isn't always a viable method on the object. It also means that there's now a situation where you can pass two arguments that relate to the same filter. Add on the potential security implications and it doesn't seem worth taking on.

**Comment by AaronLasseigne** [comment]
I'm doing this in the 3.6 release with a new filter type called `record`. It accepts records of the correct object type or a value to find the record with. By default it'll use `find` on the given class and pass it the value if it's not the correct type.

```rb
record :user
```

You can pass that `User.first` or `1` in which case it'll call `User.find(1)`.

**Comment by ngan** [comment]
Would be cool if you could do:

```
record :user, persisted: true/false
```

And it validates that the record is persisted or not.

**Comment by antulik** [comment]
and while we are at it, it's worth mentioning `global_id` support

**Comment by AaronLasseigne** [comment]
@ngan You can handle that with regular validations.

@antulik `global_id` is for when you need both a type and an id to find something. In this case, we'd already have the type (e.g. `record :user`), we only need the id. I'm not sure how often someone would want to pass a `global_id`.
