### ISSUE TITLE
JSON API errors code support

### ISSUE THREAD

**Issue by arefaslani** [AaronLasseigne/active_interaction#426]
I want to show error `code` in JSON response [as JSON API describes](http://jsonapi.org/format/#errors). How can I add code in response? I render API errors like this:
`render json: outcome.errors, status: :unprocessable_entity`
how can I put error `code` in response?

**Comment by AaronLasseigne** [comment]
If you're trying to get specific output like that, you'll need to wrap your output (i.e. `outcome.errors`) to return the JSON you want.
