### ISSUE TITLE
Recommended way to mock the result of an ActiveInteraction

### ISSUE THREAD

**Issue by BastienL** [AaronLasseigne/active_interaction#428]
Let's say I want to test `function_a`, which depends on an ActiveInteraction named `Square`:
```
def function_a(x)
  outcome = Square.run(x: x)

  if outcome.result == 4
    puts "result is 4"
  else
    puts "result is not 4"
  end
end
````
 
I'd like the test of `function_a` to be isolated from the result `Square.run`. As the result of the execution of an ActiveInteraction is a complex object, I wanted to know if there was a simple way to fake a result from an ActiveInteraction execution?

**Comment by ngan** [comment]
I think if the functionality is so isolated, you’re better off moving it into a class method on the model, or to a library.

**Comment by BastienL** [comment]
I'm sorry but I don't get your point. What if I want to test a function that calls an ActiveInteraction, without testing the ActiveInteraction in the meantime?

**Comment by tfausak** [comment]
I would personally advise against using mocks. Regardless, if you're using RSpec you can use [rspec-mocks](http://rspec.info/documentation/3.6/rspec-mocks/):

``` rb
allow(Square).to receive(:run).and_return(4)
```

**Comment by BastienL** [comment]
Well, not exactly. Because in my previous example, if I mocked the result of `Square.run(x)` to return `4` (as @tfausak suggested), `outcome.result` would obviously return a `NoMethodError: undefined method `result' for 4:Fixnum`.

**Comment by tfausak** [comment]
Oh, right. You could use a double:

``` ruby
allow(Square).to receive(:run).and_return(double(result: 4))
```

You might have to stub out more than `result` depending on what your code looks like. 

Alternatively you could return a real outcome with the result set to what you want:

``` ruby
allow(Square).to receive(:run) do
  outcome = Square.new
  outcome.result = 4
  outcome
end
```

**Comment by BastienL** [comment]
Sounds like the best solution! Thanks @tfausak
