### ISSUE TITLE
Accessing associations in rails new view

### ISSUE THREAD

**Issue by mbajur** [AaronLasseigne/active_interaction#430]
Hello!

I'm trying to use this brilliant gem and encountered a blocker. I have a `Post` model with `acts_as_taggable_on` plugin enabled. I have created a basic interaction for creating a new `Post` but my form is handled by a javascript framework (Vue.js) so i need to pass all the attributes and some additional stuff to my Vue.js component. Which basically goes down to using `to_json` here and there in the new-form view.

My controller action looks like that:

```
  def new
    @post = Posts::Create.new
  end
```

And my `Posts::Create` interaction is mostly 1:1 clone of the example taken from README. And now, when i'm trying to access associated attributes for my `@post`, rails throws that method does not exist.

For example - while trying to call `@post.tags.to_json(only: [:id, :name])` throws 

> undefined method `tags' for #<Posts::Create:0x007fb8a1617b58>

while i'm totally able to use `Post.last.tags.to_json(only: [:id, :name])`. Is there any way to deal with that? Any temporary dirty-hacks highly appreciated :)

Thanks in advance!

**Comment by AaronLasseigne** [comment]
The object you get back is an instance of `Posts::Create` not an instance of `Post` which is why the `tags` method isn't there.

How are the tags added to your newly created post?

**Comment by mbajur** [comment]
> The object you get back is an instance of Posts::Create not an instance of Post

yeah that's exactly what i was thinking. I was just sure i'm able to access the initialized `Post` object somehow.

> How are the tags added to your newly created post?

There are a lot of ways to do this using this plugin but i'm using 

```
Post.new(tag_list: 'one, two, three')
```

**Comment by AaronLasseigne** [comment]
When I asked how the tags were added, I should have been more clear. I meant, how are they added within the interaction? You'll have access to all of the inputs on an interaction so if you're passing them in, you can reference them that way.

```ruby
@post = Posts::Create.new(tags: %w[one two])
@post.tags # => ['one', 'two']
```

**Comment by mbajur** [comment]
Well, i kind of answered what you wanted me to answer :) Basically, `acts_as_taggable_on` let's user assign tags as a comma separated string. After that, you can access the tags by using `post.tags` and it will return an active recrd collection. So using default activerecord attempt, it behaves like that:

```
post = Post.new(tags_list: 'one, two')
post.tags
=> ['one', 'two']
```

My expected behaviour of interactor is:

```
post = Posts::Create.new(tags_list: 'one, two')
post.tags
=> ['one', 'two']
```

But, for some reason, interaction does not supports the association / helper accessor so `tags` is undefined and that's what error says.

**Comment by AaronLasseigne** [comment]
Are you using `acts_as_taggable_on` on `Posts::Create`?

**Comment by mbajur** [comment]
Exactly. Well, not exactly on `Posts::Create` but on `Post` model

**Comment by AaronLasseigne** [comment]
The item you get back doesn't wrap the `Post` model so it doesn't give you access to everything that an instance of `Post` has. If you want to do that you'd have to delegate calls from `Posts::Create` to `Post`.

**Comment by mbajur** [comment]
Is there any chance you could give some example or point me anywhere on how to do such thing in active_interaction? :) I have absolutely no clue how to even start

**Comment by AaronLasseigne** [comment]
Rails has a [`delegate`](https://devdocs.io/rails~5.0/module#method-i-delegate) method.

Ruby also has several ways to delegate. Your best bet for that would be to search and read up on the options.
