### ISSUE TITLE
Boolean default true issue

### ISSUE THREAD

**Issue by antulik** [AaronLasseigne/active_interaction#431]
```ruby
class X < ActiveInteraction::Base
  boolean :x, default: true

  def execute
    x
  end
end

puts X.run!(x: false) # => true
puts X.run!(x: 'false') # => false
```
Expected behaviour:
`X.run!(x: false)` to set boolean input to `false`

**Comment by AaronLasseigne** [comment]
I just ran that on the master branch and I got `false` for `X.run!(x: false)`. What version are you using?

**Comment by antulik** [comment]
my bad, the bug was caused by our monkey patching while converting blank strings to nil :D
