### ISSUE TITLE
Type independent input

### ISSUE THREAD

**Issue by hurrycaner** [AaronLasseigne/active_interaction#433]
Is there an input type I can use to not define attribute type?
For example, I don't want to define if it's string or object, i will do some stuff if it's string and other stuff if it's an object. How can i do that?

**Comment by antulik** [comment]
@hurrycaner use `interface` input, it accepts everything by default

**Comment by AaronLasseigne** [comment]
Using `interface` is fine. FYI, it's changing slightly in 4.0.0 so it won't accept everything by default. Another option would be to use `object :foo, class: Object`. That'll accept everything that's a subclass of `Object`.
