### ISSUE TITLE
Simple form not populated when interaction invalid

### ISSUE THREAD

**Issue by mbajur** [AaronLasseigne/active_interaction#441]
I have two issues trying to use active_interaction with simple_form gem. I have a following interaction:

```
class Comments::Create < ActiveInteraction::Base
  integer :parent_id, default: nil
  integer :story_id
  string :body, default: ''
  object :account

  def to_model
    Comment.new
  end

  def execute
    comment = Comment.new(inputs)

    unless comment.save
      errors.merge!(comment.errors)
    end

    comment
  end
end
```

and a model

```
class Comment < ApplicationRecord
  validates :body, presence: true
end
```

controller:

```
    outcome = Comments::Create.run(
      parent_id: parent.id,
      story_id: params.fetch(:comment)[:story_id],
      body: params.fetch(:comment)[:body],
      account: current_user.account
    )

    if outcome.valid?
      render :show
    else
      @comment = outcome
      render :new
    end

```
And two forms to demonstrate the issue:

```
# First form
= form_for @comment do |f|
  = f.text_field :story_id

# Second form
= simple_form_for @comment do |f|
  = f.input :story_id
  = f.input_field :body
  = f.error :body
```

***

The thing is - if i'm sending a form with empty `body` and `story_id` set to 1, `valid?` method for my interaction returns `false` as expected and `errors` object is getting populated.

However, when i'm trying to display a `simple_form` for my invalid record, it is not populated with the `story_id` (or any other field sent) - the inputs are empty. Also, there is no error shown for the body field (which validates as `presence: true`, as you can see in the model).

On the other hand, the regular `form_for` populates the inputs well.

This sounds like a `simple_form` issue but when i'm trying to run the create flow without involving the `active_interaction`, `simple_form` shows errors and populates the fields perfectly well - that let's me think that i have done something wrong or encountered some active_interaction bug.

Does anything looks obviously wrong in my setup ?

**Comment by hurrycaner** [comment]
Can you check what is the error class in your controller with and without active_interaction?

**Comment by mbajur** [comment]
@hurrycaner for interactor, it's `ActiveInteraction::Errors` and for non-interactor: `ActiveRecord::Errors`

I think i found what's the reason of this glitch - i have a `string :body, default: nil` input defined in my interaction. When sending empty body (which is read as `""`, not `nil`), active_interaction treats it as an invalid input for some reason (i have `default: nil` defined so it should leave empty input alone but, on the other hand, the input is not `nil` but an empty string - i can't properly explain it but i have a strong feeling it's heavily connected with that fact).

What could be done - i could check if body is empty in the controller (or any other place i'm using this interaction) and pass nil if it is. However, it would be great to do such sanitization on the interactor side to embrace the DRY pattern and keep everyhing related to comment creation in one place.

Is such thing even possible ?

**Comment by mbajur** [comment]
Unfortunatelly - after passing `nil` as body instead of empty string, the error is still there and the form is still not displaying the form errors properly.

No matter if i put body presence validation in interactor or in a model - my interactor returns `ActiveInteraction::Errors` instance in `errors` and form is not filled with data / there are no error messages visible along each invalid field.

**Comment by mbajur** [comment]
Sorry for a third comment in a row but i created a simple app to demonstrate this issue:

https://github.com/mbajur/active-interaction-simple-form-broken-demo

(repro steps and setup instructions are in the README)

**Comment by hurrycaner** [comment]
@AaronLasseigne Can you help us?

**Comment by AaronLasseigne** [comment]
The underlying issue is that you're switching between `Comment` and `Comments::Create`.

Here's a fix:
https://github.com/AaronLasseigne/active-interaction-simple-form-broken-demo/commit/c4a115fec6b02787b4617e40032f67699cbb549e

**Comment by mbajur** [comment]
Yup that was it :) Thank you guys! For the record (if @AaronLasseigne fork get removed one day):

1. In your `new` controller action, use `Comments::Create.new` instead of `Comment.new`
2. Remove `to_model` method from the interaction
3. in `simple_form_for` helper call, set `as: :comment` and `url: comments_path`
