### ISSUE TITLE
Validation message is not correct

### ISSUE THREAD

**Issue by mingca** [AaronLasseigne/active_interaction#442]
In my interaction
`errors.merge!(comment.errors)`

In comment model
`validates :comment, presence: { message: '^Please provide a valid comment'._ }`

But validation result that I get from outcome.errors.full_messages is `Comment can't be blank` which is the default activerecord validation message not the customized one.

**Comment by ninjarails** [comment]
My work around was ```rescue ActiveRecord::RecordInvalid => invalid
      # https://github.com/AaronLasseigne/active_interaction/issues/442
      invalid.record.errors.messages.each do |column, messages|
        messages.each { |m| errors.add(column, m) }
      end```

**Comment by ninjarails** [comment]
So basically I need the former behavior here: #417

**Comment by AaronLasseigne** [comment]
This is really the same issue as #435 where `:message` wasn't being accounted for. There's a fix coming in the next release.
