### ISSUE TITLE
Can we have `#run` method instead of `#execute` ?

### ISSUE THREAD

**Issue by Samemura** [AaronLasseigne/active_interaction#448]
Just simple question / idea, we define `#execute` for the logic, and it will be called via `.run` .
If it could be defined as `#run`, it will be nicer to understand.

Is that not so good ? Or hard to change ? Maybe it should be alias of `#execute` for 1st step.

**Comment by AaronLasseigne** [comment]
I agree with @formigarafa on this. We want to distinguish the two because of the other things happening. Right now that still seems like the best approach. Thanks for the question though.
