### ISSUE TITLE
Return value for `.run` and `.run!`

### ISSUE THREAD

**Issue by Samemura** [AaronLasseigne/active_interaction#449]
I think return values for `.run` and `.run!` are better to be same like `ActiveRecord.create` .

Current behavior is: (I am not sure)
`.run` => return as `#execute` method ?
`.run!` => return ActiveInteraction class ??

How do you think ??

By the way, I like this nice gem, thank you.

**Comment by antulik** [comment]
@Samemura they used differently. `.run` is useful when we need to return the result along with any error messages. E.g. in controllers

```ruby
def show 
  outcome = CreateUser.run(params)
  if outcome.valid?
    outcome.result
    # ...
  end
end
```

**Comment by AaronLasseigne** [comment]
As @antulik said, `run` and `run!` are used differently. When you call `run` you're getting back the response from `execute` along with any errors that may have occurred. With `run!`, the expectation is that all of the input is correct and you just want the return back from `execute`. If anything does fail, an error is thrown. It's kind of like Rails `save` vs `save!`.

Thanks for the question and I'm glad you like the gem.
