### ISSUE TITLE
Rails : Merging nested attributes errors failed with method missing

### ISSUE THREAD

**Issue by rahulknojha** [AaronLasseigne/active_interaction#450]
I have model called Supplier and it has nested attributes for the address. when adrees attributes are invalid. and I try to merge supplier errors to errors of interaction it leads to method missing.

Please find my code below.
```
def execute
    supplier = Supplier.new(supplier_params)
    supplier.address_attributes = address_attributes if address_attributes?
    
    return errors.merge! supplier.errors unless supplier.save

    supplier
end

```

Please find error below

`
Failure/Error: return errors.merge! supplier.errors unless supplier.save
     
     NoMethodError:
       undefined method `address.state' for #<Supplier:0x0000000006ff9780>
       Did you mean?  address

`

**Comment by AaronLasseigne** [comment]
It looks like the nested attributes aren't available for some reason. There's not enough here for me to really tell what's going on. What does the error object look like before you try merging it?

**Comment by AaronLasseigne** [comment]
It's possible this was fixed at some point. I've added a test for nested errors but it appears to be working fine.
