### ISSUE TITLE
Is there a way to prevent error strings from localizing?

### ISSUE THREAD

**Issue by arianf** [AaronLasseigne/active_interaction#452]
This is cool and all if you are bubbling up the error to the user

```ruby
class I18nInteraction < ActiveInteraction::Base
  string :name
end

I18nInteraction.run(name: false).errors.messages[:name]
# => ["is not a valid string"]

I18n.locale = :hsilgne
I18nInteraction.run(name: false).errors.messages[:name]
# => ["gnirts dilav a ton si"]
```

But is there a way to turn this off, if you plan to raise the error? Doesn't make sense just because the user was using French, for the error message to be in French when all the code we write is in English lol especially since we use Sentry to aggregate our error messages.

```ruby
I18n.locale = :fr
I18nInteraction.run!(name: false)
ActiveInteraction::InvalidInteractionError (Name a un type invalide (chaîne de caractères))
```

**Comment by arianf** [comment]
Probs not the best way to solve this problem, but here is a monkey patch I came up with.

```ruby
FORCE_LOCALE = :en

class ActiveInteraction::Errors
  def add(attribute, message = :invalid, options = {})
    options[:locale] = FORCE_LOCALE
    super(attribute, message, options)
  end
end

module ActiveInteraction
  module Validation
    class << self
      def type(filter)
        I18n.translate("#{Base.i18n_scope}.types.#{filter.class.slug}", locale: FORCE_LOCALE)
      end
    end
  end
end
```

**Comment by AaronLasseigne** [comment]
There's not a good way that I'm aware of. Assuming that you're using Rails, what do you do with errors that arise from models? Wouldn't you have the same issue using `save!` with them?

**Comment by arianf** [comment]
Yea, that I guess that is true. Hmmm, okay, I'll file a bug with rails instead.
