### ISSUE TITLE
I18n.available_locales is being modified by active_interaction

### ISSUE THREAD

**Issue by arianf** [AaronLasseigne/active_interaction#456]
Because you guys have a locale folder, this gem adds the following locales to your available locale list

```ruby
I18n.available_locales
[:"pt-BR", :it, :en, :fr]
```

Is it possible for active_interactions not to pollute `I18n.available_locales`?

https://github.com/AaronLasseigne/active_interaction/blob/2eb26949676057a8112bdc4295583c1229f70b9a/active_interaction.gemspec#L32-L34

Line 34 should be removed.

**Comment by AaronLasseigne** [comment]
Yup, let me make sure that doesn't break anything.

**Comment by AaronLasseigne** [comment]
From what I can tell, it looks like if the files are included in any way I18n assumes those locales are available. I think we'd have to remove the locales entirely. I'm not sure how to make them available in a useful way without polluting the list of available locales.
