### ISSUE TITLE
datetime doesn't support ActiveSupport::TimeWithZone

### ISSUE THREAD

**Issue by wayne5540** [AaronLasseigne/active_interaction#460]
`date_time` doesn't support `ActiveSupport::TimeWithZone` for now. Any plan to support this? 

It seems #40 add `TimeWithZone` support to `time` but not `date_time`

Thanks.

## Reproduce

* active_interaction: 3.6.2
* rails: 5.2.1

### Expected behaviour:

In rails console:

```rb
class Interaction < ActiveInteraction::Base
  date_time :t

  def execute
  end
end

puts Interaction.run(t: Time.current).errors
# => []
```

### What actually happen

```rb
class Interaction < ActiveInteraction::Base
  date_time :t
end

puts Interaction.run(t: Time.current).errors.full_messages
# => T is not a valid date time
```

**Comment by AaronLasseigne** [comment]
Is there a reason to avoid using `time`?

**Comment by wayne5540** [comment]
Good point, I thought `time` wasn't include `date` since there are `date_time` and `time`, I'll use `time` instead of `date_time`. Thanks @AaronLasseigne
