### ISSUE TITLE
Hash removes keys before type check

### ISSUE THREAD

**Issue by elkesrio** [AaronLasseigne/active_interaction#461]
For a `Hash` type the keys that aren't specified are removed before the type check. I think they should be removed during the type check:

```ruby
class HashInteraction < ActiveInteraction::Base
  hash :preferences do
    boolean :newsletter
    boolean :sweepstakes
  end

  set_callback :type_check, :before, -> { puts inputs }
 set_callback :type_check, :after, -> { puts inputs }

  def execute
    true
  end
end
```

**Actual behavior**
```ruby
HashInteraction.run(preferences: { newsletter: true, sweepstakes: true, unspecified: "toto" })
# { newsletter: true, sweepstakes: true }
# { newsletter: true, sweepstakes: true }
```

**Expected behavior**
```ruby
HashInteraction.run(preferences: { newsletter: true, sweepstakes: true, unspecified: "toto" })
# { newsletter: true, sweepstakes: true, unspecified: "toto" }
# { newsletter: true, sweepstakes: true }
```

**Comment by AaronLasseigne** [comment]
Why?

**Comment by elkesrio** [comment]
Because it makes more sense. It belongs to the process of type checking. It gives more control on your inputs.

**Comment by AaronLasseigne** [comment]
I think it makes more sense that they're removed prior to type checking. Type checking is not for sanitizing. If you want these inputs you can use [`striped: false`](https://github.com/AaronLasseigne/active_interaction#hash).
