### ISSUE TITLE
Using dry-schema for input validation and coercion

### ISSUE THREAD

**Issue by jhund** [AaronLasseigne/active_interaction#464]
Hi there, I absolutely love the ActiveInteraction gem. It allows me to structure my Rails app interactions in a way that makes perfect sense to me.

One area where I feel some friction is validating and coercing deeply nested Hash inputs. I get those when interacting via JSON with a client side JS app.

I know that the [dry-schema](https://dry-rb.org/gems/dry-schema/) or [dry-validation](https://dry-rb.org/gems/dry-validation/) gems would let me handle more complex validation scenarios. Have you considered allowing usage of either of the two instead of the ActiveInteraction built in validation and coercion?

**Comment by AaronLasseigne** [comment]
The goal of this gem has always been to fit nicely into Rails. Moving to a different validation system would add friction with Rails. I don't think this is in the cards.
