### ISSUE TITLE
Composed interaction errors are merged to base 

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [AaronLasseigne/active_interaction#466]
I dunno why, but as far as I know since Rails 5 error messages are nestable (see https://blog.bigbinary.com/2016/07/07/errors-can-be-indexed-with-nested-attrbutes-in-rails-5.html) and it looks like it's not working correctly?

ActiveInteractor is merging them to base though, which is wrong in my opinion.. 

Please correct me, but for me this seems like a bug (which prevents a certain use case for me right now)?

```ruby
class ChildInteraction < ActiveInteraction::Base
  array :data do
    object class: Fixnum
  end

  def execute
    errors.add("data[1]", "tessst")
  end
end

class RootInteraction < ActiveInteraction::Base
  array :data do
    object class: Fixnum
  end

  def execute
    compose(ChildInteraction, data: data)
  end
end

RootInteraction.run(data: [1,2,3]).errors.to_h

=> {:base=>"Data[1] tessst"}

instead of

=> {"data[1]"=>"tessst"}
```

I tried it by setting ```config.active_record.index_nested_attribute_errors =  true``` like mentioned in the link above, but it doesn't work either..?

**Comment by ivdma** [comment]
Same here when model errors details are merged into interaction error details:

```ruby
class DoStuff < ActiveInteraction::Base
  record :some_input_model

  def execute
    if some_model.valid?
      do_stuff
    else
      # Next line fails to merge details with their keys, 
      # instead it adds translated errors to `base`
      errors.merge! some_model.errors 
    end
  end

  private

  def some_model
    some_input_model.some_relation.new some_argument: 'with invalid input'
  end
end
```

**Comment by AaronLasseigne** [comment]
This has been fixed in https://github.com/AaronLasseigne/active_interaction/commit/bc84b69a61ebb71be9f495c598ee7def65d9c4fa. It'll be part of the 5.0.0 release.
