### ISSUE TITLE
Errors from the interactions, composed in the callbacks lead to uncaught exception

### ISSUE THREAD

**Issue by TolichP** [AaronLasseigne/active_interaction#468]
I have an interaction, that uses `compose` in its callback. If there are some errors, returned from inner interaction - the `ActiveInteraction::Interrupt` exception is thrown and caught nowhere.

Example:

```
class ChildFailingInteraction < ActiveInteraction::Base       
  def execute
    errors.add(:base)
  end
end

class ParentInteraction < ActiveInteraction::Base
  set_callback :execute, :before, :composing_failing_interaction

  def composing_failing_interaction
    compose(ChildFailingInteraction)
  end
        
  def execute; end
end
```

Calling `ParentInteraction.run` leads to `ActiveInteraction::Interrupt` exception.
If the `compose(ChildFailingInteraction)` is placed in the `execute` - it's okay and the exception is caught.

**Comment by TolichP** [comment]
Any updates? Can I try to fix it myself and make a PR?

**Comment by AaronLasseigne** [comment]
We use the callback system provided by ActiveModel. That means we don't have control over how the callbacks are run. We call `run_callbacks(:execute)` and it happens. That means the only way to this is to wrap that call:

```rb
begin
  run_callbacks(:execute) do
     # ...
  end
rescue Interrupt => interrupt
  # ...
end
```

The issue with that is none of the other callbacks will execute. So, if you've added more than one before callback or have an after callback, they might not get called.

The best thing to do is probably to catch the error in the before callback:

```rb
class ParentInteraction < ActiveInteraction::Base
  set_callback :execute, :before, :composing_failing_interaction

  def composing_failing_interaction
    compose(ChildFailingInteraction)
  rescue ActiveInteraction::Interrupt => interrupt
    errors.merge!(interrupt.errors)
  end
        
  def execute; end
end
```

I think that'll have the effect your looking for.

If you can think of a way to fix it let me know.
