### ISSUE TITLE
Allow having filters with reserved name

### ISSUE THREAD

**Issue by krzyzak** [AaronLasseigne/active_interaction#471]
Hello,

I'm migrating some old (3.0.1) codebase, and I encountered one unexpected issue.

on 3.0.1 this interactor works just fine:
```ruby
Class.new(ActiveInteraction::Base) { boolean :open, default: false }
```

Whereas on 3.7 (actually on anything >= 3.2.1) it fails:

```ruby
[2] pry(main)> Class.new(ActiveInteraction::Base) { boolean :open, default: false } 
ActiveInteraction::InvalidFilterError: "open" is a reserved name
```

I investigated that a bit, and it comes from <a href="https://github.com/AaronLasseigne/active_interaction/blob/master/lib/active_interaction/modules/input_processor.rb#L21">this particular check in InputProcessor</a>.

While I understand why it might be potentially dangerous to have such collisions, I'm wondering if there shouldn't be an option to allow me to have a filter with _reserved name_. I'm totally fine with keeping current behaviour as default, of course, so this should be more like a enhancement than a breaking change - wdyt?

**Comment by AaronLasseigne** [comment]
I'm not sure about allowing an override. Maybe I can rename some internal methods to reduce the chance of collisions with popular names.

**Comment by krzyzak** [comment]
I have three reasons why it should be allowed:

First (this is just my point of view, but) no tool should be smarter than a programmer: if I know what I'm doing, the tool shouldn't prevent me from doing that. I guess that ActiveInteraction is addressed to skilled programmers rather than to newbies to prevent them to accidentally shoot themself in the foot.

Second, which is less like a matter of personal taste, but more practical: There are some methods in stdlib that I'd say it's extremely rare that you'd like to use them in the context of an Interactor, but have names, that are likely to be used in interactors. `hash` is useful in comparators, but I doubt you'll ever need that in interactor. However, when processing some data from payments provider, it's quite likely that you'll get `hash` from them (which will be a string). Same with `open` - I can't think of any reasonable example when you'd like to open something in your interactor (and even if you'd like to, you can always call `Kernel.open`), but there are many domains where `open` attribute makes sense imo.

Third reason is more about maintainability: When you have big application that uses ActiveInteraction, it's just a matter of time when you'll add new gem that extends base scope and will provide naming clash: If you don't have a way to override your filter name, you have two options: either you don't use that new gem you wanted to use (which sometimes might be really painful), or you have to refactor your Interactor to use another filter name (which also might be hard to refactor).

**Comment by AaronLasseigne** [comment]
You do make some good points. I've relaxed the check so that it's only looking at things on `ActiveInteraction::Base` and not everything that comes along with `Object`. This should open up the naming and still provide pretty good safety. It'll be in the 3.8.0 release.
