### ISSUE TITLE
Add limit on integer value

### ISSUE THREAD

**Issue by navid-farjad** [AaronLasseigne/active_interaction#475]
I think it is a very good idea to have a limit option in inputs:
if you think it is I can make a pull request. 

For example: 
```
class Account::Index < ActiveInteraction::Base
  integer :page, default: 1
  integer :per_page, default: 30, limit: 100
```

**Comment by tfausak** [comment]
I think you can do this with validations.

``` rb
class Account::Index < ActiveInteraction::Base
  integer :per_page
  validates :per_page, numericality: { less_than_or_equal_to: 100 }
```

https://github.com/AaronLasseigne/active_interaction/tree/v3.7.1#validations
