### ISSUE TITLE
compose with file name & line number

### ISSUE THREAD

**Issue by robturtle** [AaronLasseigne/active_interaction#479]
```ruby
class OneDay
  def execute
    compose(Eat)
    compose(Coding)
    compose(Sleep)
  end
end
```
Image if errors happened, there's no good way to tell where exactly the location the error happened in the first place. Especially when each sub-interactions also have its composed interactions. Basically the backtrace from the top-level interaction to the first scene of the errors will be swallowed.

It'd good if 
1. the errors remember the `__FILE__` and `__LINE__` of where `errors.add` happens
2. when merging errors from the composed sub-interaction, it should retain the file location info in the errors
3. probably the best place to save such info is in `detailed_messages`?

**Comment by rakibulislam** [comment]
@robturtle Did you consider submitting this as an issue in the original gem's github issues? They may like the idea since it will improve the error handling greatly and decide to implement this!

**Comment by AaronLasseigne** [comment]
I'm not sure how I'd go about doing this. I don't think I can force that information into the backtrace.

**Comment by robturtle** [comment]
I think the easiest way is via https://stackoverflow.com/a/37135337/2214973.

**Comment by robturtle** [comment]
I didn't look into the source yet. It depends on when does the exception being raised if `run!` failed.

1. If it raises at the first scene, we can simply use `set_backtrace(caller)`;
2. If the failed sub-interaction first return back to the top-level interaction and raise afterward, then the sub-interaction should wrap its `caller` information way up to the top-level.

It'd be great if you could show me what are the related files. Otherwise, I will read the source code someday which will be slower.
