### ISSUE TITLE
Unexpected behavior with hash and interface keys

### ISSUE THREAD

**Issue by paul-mannino** [AaronLasseigne/active_interaction#480]
Short example to reproduce (using 3.8.0):
```
require 'active_interaction'

class Foo < ActiveInteraction::Base
  hash :bar do
    interface :baz1
    interface :baz2
  end

  def execute
    bar
  end
end

bar = { 'baz1' => 1, 'baz3' => 3 }

puts Foo.run!(bar: bar)
# prints {"baz1"=>1, "baz3"=>3}
```
I might have missed something in the docs, but I would expect this to raise an error or filter out baz3 from the hash. What actually happens is that no filtering seems to be taking place.

Happy to submit a patch if this is indeed a bug :)

**Comment by tfausak** [comment]
Which error did you expect to be raised here?

**Comment by paul-mannino** [comment]
> Which error did you expect to be raised here?

Thinking about this more, an error isn't the right behavior because interface should accommodate a missing key.  Still surprised that no filtering is happening. 
For instance, this small tweak allows the hash to be filtered:
```
  hash :bar do
    interface :baz1
    interface :baz2, **default: nil**
  end
```
returns `{"baz1"=>1, "baz2"=>nil}`, which makes a bit more sense to me.

**Comment by tfausak** [comment]
Oh, I missed that your input was called `baz2` but you passed in a `baz3` key. That extra key should be getting filtered. @AaronLasseigne you might want to look at this.

**Comment by AaronLasseigne** [comment]
It looks like the issue is that the error is being suppressed when using `interface`.

```ruby
class Foo < ActiveInteraction::Base
  hash :bar do
    interface :baz1
    interface :baz2
  end

  def execute
    bar
  end
end

class Foo2 < ActiveInteraction::Base
  hash :bar do
    integer :baz1
    integer :baz2
  end

  def execute
    bar
  end
end

> Foo.run!(bar: { baz1: 1, baz2: 2, baz3: 3})
=> {"baz1"=>1, "baz2"=>2}

> Foo.run!(bar: { baz1: 1, baz3: 3})
=> {:baz1=>1, :baz3=>3}

> Foo2.run!(bar: { baz1: 1, baz3: 3})
Traceback (most recent call last):
        ...
ActiveInteraction::InvalidInteractionError (Bar has an invalid nested value ("baz2" => nil))
```

@paul-mannino do you want to take a stab at fixing it?

**Comment by paul-mannino** [comment]
@AaronLasseigne yeah, I'll take a crack at it

just want to make sure I'm clear on intended behavior. So this should in fact raise an error? Only reason I ask is that interface normally allows you to not pass anything:
```
require 'active_interaction'

class Foo < ActiveInteraction::Base
  interface :bar

  def execute
    bar
  end
end

puts Foo.run!
```

The alternate route would just be to fix the filtering that isn't happening, and potentially add the key as a nil.

**Comment by AaronLasseigne** [comment]
That's a great question. I'm kind of thinking that your example should throw an error. With `interface :bar` you're saying anything is fine but you're not passing anything. You're passing nothing. It seems like that should be an error. 🤔

**Comment by tfausak** [comment]
For what it's worth, the documentation explicitly shows an example of an `interface` field succeeding when passed nothing: https://github.com/AaronLasseigne/active_interaction/tree/a2d6399b65c4925f4c8024ae391ee240284f32c2#interface

``` rb
class InterfaceInteraction < ActiveInteraction::Base
  interface :anything
  def execute
    anything.class
  end
end
InterfaceInteraction.run!
# => NilClass
```

In fact, I think we pretty explicitly allow this. See #265. 

I could see an argument that `Foo.run!()` is different than `Foo.run!(bar: nil)`. Is that distinction worth making?

**Comment by paul-mannino** [comment]
yes, to me the most consistent behavior with the how interface works in the docs would be a return value of `{"baz1"=>1, "baz2"=>nil}` or `{"baz1"=>1}` for the example I put in the OP. Probably only a practical difference between the two in certain edge cases.

**Comment by AaronLasseigne** [comment]
I think it makes the best sense for `nil` to fail even for a completely open interface.
