### ISSUE TITLE
Support Rails 6.1 in 3.8.x 

### ISSUE THREAD

**Issue by tomasdundacek** [AaronLasseigne/active_interaction#497]
Hi,

couple of weeks ago, I have submitted PR #492 for adding support for Rails 6.1 which was subsequently merged in to version 4 branch of AI. Would it be possible to release a patch version in 3.8.x with this code as well? I'm happy to resubmit the PR if needed.

On my project, I need to update both Rails and active_interaction eventually, but due to breaking changes in AI, I would rather update these one by one.

Thanks

**Comment by AaronLasseigne** [comment]
Couldn't you update AI first? Rails 5+ is still supported.
