### ISSUE TITLE
autoload

### ISSUE THREAD

**Issue by alec-c4** [AaronLasseigne/active_interaction#502]
Hey, 
As I know - rails [should autoload](https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#autoload-paths) all classes within the app directory and all sub-directories. What's wrong with AI, why should I to add 

`    config.autoload_paths += Dir.glob("#{config.root}/app/interactions/*")`

**Comment by AaronLasseigne** [comment]
It's possible that this advice is simply out of date. If the line isn't needed then I'm happy to remove that from the README.

**Comment by alec-c4** [comment]
@AaronLasseigne it should, but it won't work :( I still need to manually set autoload_path
