### ISSUE TITLE
Use default on `record` filter when given an empty string

### ISSUE THREAD

**Issue by solebared** [AaronLasseigne/active_interaction#503]
Thanks for fixing #412 in v4, this really does help with using AI for form objects.

It appears however that 5a5337cf886372362a286a38b476aeab129829f2 did not cover `record` filters? Perhaps this was intentional, but i think treating a blank/empty input string as `nil` could also apply here.

For example, say we have a form for creating an `Issue`,
```
class IssueForm < ActiveInteraction::Base
  record :assignee, class: Contributor, default: nil
  # ...
end
```
where `assignee` is selected with a dropdown on the frontend, but is optional.

When the user omits the assignee, `params` would still include `assignee: ''`.
Passing params directly into the interactor would then fail:
```
IssueForm.run!(assignee: '')  #=> ActiveInteraction::InvalidInteractionError (Assignee is not a valid record)
```

I think it would be intuitive for AI to assign the default value here, as is the case with other filters.

**Comment by exbinary** [comment]
Attempted to also demonstrate this with a unit test in [this commit](https://github.com/exbinary/active_interaction/commit/cff812dddc1e2c387462bb43721e5e438a394d49), though i'm not confident this is the right place to specify the behavior i'm proposing.

**Comment by AaronLasseigne** [comment]
This will be in the `5.0.0` release.
