### ISSUE TITLE
Is it possible to send a polymorphic object to an interaction?

### ISSUE THREAD

**Issue by philippemoro** [AaronLasseigne/active_interaction#504]
Title says it all, I'm creating an interaction called `CreateEvent`,  event can belong to either a `Customer` or to a `Company`.

Is it possible to create an interaction with an `object` argument that accepts two different classes as param?

**Comment by AaronLasseigne** [comment]
They would have to have a common ancestor or interface. That would allow you to use `object` or `interface` respectively.
