### ISSUE TITLE
ArrayFilter#add_option_in_place_of_name forces from option for InterfaceFilter

### ISSUE THREAD

**Issue by sholden** [AaronLasseigne/active_interaction#505]
If you specify `methods` in an interface filter inside an array like this:

```
array :inputs do
  interface methods: %i{to_s}
end
```

ArrayFilter will try to insert `from: Input`, raising an exception in InterfaceFilter bc both from and methods are defined.

**Comment by kylemellander** [comment]
I am also running into this issue.
