### ISSUE TITLE
Hash parameters do not work outside of Rails

### ISSUE THREAD

**Issue by HashNotAdam** [AaronLasseigne/active_interaction#510]
When using vanilla Ruby, including hash parameters does not work because the `with_indifferent_access` method has not been patched onto hashes and is required by `lib/active_interaction/filters/hash_filter.rb`. This is solved by:
```
require "active_support/core_ext/hash/indifferent_access"
```

Simple example:
```
require "active_interaction"

module ActiveInteractionTest
  class Interaction < ActiveInteraction::Base
    hash :parameters

    def execute
      puts "All is fine"
    end
  end
end
```

```
ActiveInteractionTest::Interaction.run(parameters: {})
/Users/arice/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/active_interaction-4.0.3/lib/active_interaction/filters/hash_filter.rb:47:in `adjust_output': undefined method `with_indifferent_access' for {}:Hash (NoMethodError)
```

**Comment by AaronLasseigne** [comment]
I actually happened across this the other day (https://github.com/AaronLasseigne/active_interaction/commit/2d8ee0a64f83bfb396f3f45673150a3c3a66cc9a). It'll be in the next release. Thanks for reporting it though!
