### ISSUE TITLE
Achieve `exclusive disjunction` between two given inputs

### ISSUE THREAD

**Issue by alexbrebu** [AaronLasseigne/active_interaction#513]
The question comes from a need we had:
```ruby
  module Cars
    class FindCar< BaseUseCase
      object :dealer, class: Dealer
      string :category_id_or_name
    end
  end
```

The issue here is that `:category_id` is actually an integer and `:name` a string. So we would have needed something that allows both integer or string to be passed through that input key:

```ruby
    integer || string :category_id_or_name
```

**Comment by alexbrebu** [comment]
The solution we came up with is:
```ruby
  module Cars
    class FindCar< BaseUseCase
      object :dealer, class: Dealer
      integer :category_id, default: nil
      string :uuid, default: nil

      validates :uuid, presence: true, unless: :category_id, strict: true
      validates :category_id, presence: true, unless: :uuid, strict: true
    end
  end
```

**Comment by AaronLasseigne** [comment]
The system we have isn't really a type system. It just tests and casts. I don't want to start down the path of trying to implement real typing features. You can do what's mentioned above or use `object :category_id_or_name, class: Object` which will accept both and then use validation to confirm it's one or other other.
