### ISSUE TITLE
Change of bahavior in object filter with Minitest::Mock in v4.0

### ISSUE THREAD

**Issue by thatguysimon** [AaronLasseigne/active_interaction#514]
Hi, 
I've encountered an issue while upgrading from v3.7 to v4.0 with how `Minitest::Mock` objects are cleaned by the `object` filter.

`Minitest::Mock.new` can take a delegator object which the mock object then wraps like so:
```ruby
potato_mock = Minitest::Mock.new(Potato.new)
potato_mock.some_potato_method_that_isnt_mocked
# => Minitest will delegate the method call to `Potato`
```

With ActiveInteraction v3.7, the gem played nicely with Minitest because (intentionally or not) the cleaning of a `Minitest::Mock` object which wraps `Potato` resulted in the same `Minitest::Mock` object that's sent in:

```ruby
class MyInteraction < ActiveInteraction::Base
  object :potato

  def execute
    puts potato.class
  end
end

# In a test:
potato_mock = Minitest::Mock.new(Potato.new)
MyInteraction.run!(potato: potato_mock)
# => Minitest::Mock
```

However, the same exact code with ActiveInteraction v4.0 results in a `Potato` object instead of `Minitest::Mock`:
```ruby
class MyInteraction < ActiveInteraction::Base
  object :potato

  def execute
    puts potato.class
  end
end

# In a test:
potato_mock = Minitest::Mock.new(Potato.new)
MyInteraction.run!(potato: potato_mock)
# => Potato
```

This means that any **expectations that are set on the `Minitest::Mock` object are gone** and the test will fail.

Any idea why this is happening? Is there a workaround for this?

Thanks, 
Simon

**Comment by AaronLasseigne** [comment]
I've only rarely used Minitest. No change jumps out at me as something that could cause this.

**Comment by AaronLasseigne** [comment]
Looking at this again, I think this is more of an issue with minitest than this gem.
