### ISSUE TITLE
Support for array of classes for the object filter

### ISSUE THREAD

**Issue by danilobarion1986** [AaronLasseigne/active_interaction#516]
Hey!
Wouldn't it be good to have the possibility of passing an array of classes to the `object` filter? So we could do something like this:

`object :foo, class: [Bar, Baz]`

**Comment by AaronLasseigne** [comment]
It seems like you'd be better off using a parent class and referencing that or using `interface` to make sure they behave the same. If that doesn't meet your need though, the extras extension should do the trick.
