### ISSUE TITLE
Rails 7 support

### ISSUE THREAD

**Issue by spencersteiner** [AaronLasseigne/active_interaction#518]
Rails 7 depends on activemodel 7.0.0, and active interaction requires activemodel (>= 5, < 7). 

Here's the bundler output when upgrading rails with active interaction installed:
```
Bundler could not find compatible versions for gem "activemodel":
  In Gemfile:
    active_interaction (~> 4.0) was resolved to 4.0.6, which depends on
      activemodel (>= 5, < 7)

    rails (= 7.0.0) was resolved to 7.0.0, which depends on
      activemodel (= 7.0.0)
```

**Comment by AaronLasseigne** [comment]
closed by https://github.com/AaronLasseigne/active_interaction/pull/519
