### ISSUE TITLE
autoload paths 

### ISSUE THREAD

**Issue by alec-c4** [AaronLasseigne/active_interaction#522]
Hey!
Is it possible to create an initializer for rails application and put it to config/initializers instead of adding to application.rb `config.autoload_paths += Dir.glob("#{config.root}/app/interactions/*")` ? I've tried to do so

```Rails.application.config.autoload_paths += Dir.glob("#{Rails.application.config.root}/app/interactions/*")```

 but it doesn't work :(

**Comment by AaronLasseigne** [comment]
I would have thought that would work. I'm not sure why it wouldn't. Maybe something to do with the order things are loaded?

**Comment by AaronLasseigne** [comment]
It's worth noting that in newer versions of Rails you shouldn't even need that line anymore.

**Comment by alec-c4** [comment]
@AaronLasseigne rails 7.0.2.3 - this line is still required

**Comment by AaronLasseigne** [comment]
I was able to create a new Rails app (7.0.2.3), add the gem, add the "interactions" directory under "app", create an interaction, and use it from the console. No config changes needed.

**Comment by ScotterC** [comment]
FWIW I have an interaction file autoloads within the `app/interactions/` directory but not in a sub directory `app/interactions/documents/interaction.rb`. I'm still diagnosing as to why.
