### ISSUE TITLE
Bug: Cached default input values

### ISSUE THREAD

**Issue by ericcecchi** [AaronLasseigne/active_interaction#539]
The ActiveInteraction v5 update introduced a regression where the default option for inputs is cached and not reevaluated on each execution. For default values that are function calls (e.g. lambdas), this leads to stale values after the first execution of an interaction.

The root cause of this regression is the caching of default values introduced in [this commit](https://github.com/AaronLasseigne/active_interaction/commit/a3f4058761254a713aae9914dd3e8ad2e87be512). The previous behavior should be restored by either reverting the changes in that commit or conditionally caching the default value only when the value is not a function. Since the benefits of caching static values are negligible, the best option is to revert this change.

**Comment by AaronLasseigne** [comment]
Thanks for the issue. Fixed in https://github.com/AaronLasseigne/active_interaction/releases/tag/v5.1.1
