### ISSUE TITLE
Input access consistency issues

### ISSUE THREAD

**Issue by southpaw27** [AaronLasseigne/active_interaction#555]
Hey!

I've run into a strange problem. Occasionally, I am unable to access an input like a regular parameter.

Ex.

    class Something < Interactions::ApplicationInteraction
      record :input_1, class: "::Class1"
      record :input_2, class: "::Class2"

      def execute
        # within this execute, I'm able to call
        input_1 # and the input is not nil
        
        input_2 # is nil
        
        @input_1 # is not nil
        @input_2 # is not nil
        self.input_1 # is not nil
        self.input_2 # is not nil
      end
    end

In another interaction with the same input_2 defined as a record, I'm able to access the value with 
`input_1`
and it is not nil. 

It made for a very confusing afternoon and I'm wondering if anyone has any insight. 
The call into the interaction was as follows:
`Something.run(input_1: x, input_2: y)`

For now, I'm using self to access all variables and it's working fine, just curious if anyone has insights into what might be going on? 
Thanks!

**Comment by AaronLasseigne** [comment]
Can you provide a working example?

**Comment by AaronLasseigne** [comment]
I'm going to go ahead and close this but please reopen it if you can give an example.
