### ISSUE TITLE
Something strange with full_messages method for errors

### ISSUE THREAD

**Issue by TruesSpeak** [AaronLasseigne/active_interaction#556]
Hello @AaronLasseigne ! 
Recently, the rails project at my work updated the gem and encountered strange behavior. The full_messages method outputs an empty array for errors. At the same time, messages displays correct information for errors. I patched the ActiveInteraction class with my hands::Errors, added 
![image](https://user-images.githubusercontent.com/101975442/220702326-214f5053-dcb5-4890-a011-69d5a0914ada.png) 
And everything started working, but what surprised me was that in the tests in the gem repository, the method works without problems so.
I attach screenshots
![image](https://user-images.githubusercontent.com/101975442/220703509-75d95491-5365-4bca-acf1-d87c74243f8e.png)
We up version of gem from (3.8.3) to (5.2.0) because up ruby and rails versions to 3.2.1 and 7.0.4.2 
Maybe you have any ideas how to fix it?

**Comment by AaronLasseigne** [comment]
It seems to be working for me on 5.2.0.

```ruby
class I < ActiveInteraction::Base
  string :s

  def execute
    s
  end
end

I.run.errors.full_messages
=> ["S is required"]
```

```ruby
class I < ActiveInteraction::Base
  string :s

  validates :s, length: { minimum: 2 }

  def execute
    s
  end
end

I.run(s: 'a').errors.full_messages
=> ["S is too short (minimum is 2 characters)"]
```
