### ISSUE TITLE
When use callback - compose work strange in interaction

### ISSUE THREAD

**Issue by TruesSpeak** [AaronLasseigne/active_interaction#557]
Hello. In my case I set in interaction
`set_callback :execute, :after, :pay_prepayment` or `set_callback :execute, :after, -> { pay_prepayment }`
And have 4 compose() with another interactions. When callback is commented everything is ok.
When callback is work, I have
![image](https://user-images.githubusercontent.com/101975442/222427708-f02812fe-f1b8-4fe3-a49c-1d936f3a94bc.png)
Interaction that I call at the screen - have validation, that fails.
Have idea how to fix that?

**Comment by AaronLasseigne** [comment]
Can you provide an example interaction that fails in the same way?
