### ISSUE TITLE
Array Filter with default values aren't initialized on each run

### ISSUE THREAD

**Issue by ScotterC** [AaronLasseigne/active_interaction#562]
This is surprising behavior to me but maybe my mental model is off. When setting a default value for an array, such as an empty array, it maintains state of that array between separate calls to the interaction. In the below example, I would expect each run to have a `responses` length of 1 since it is adding to an empty array each time. 

In a different scenario, with an array with default values, I'd expect those values to be initialized each time the interaction is run as well. 

```ruby
# /interactions/test_array.rb
class TestArray < ActiveInteraction::Base
  array :responses, default: []

  def execute
    responses << options.sample
  end

  def options
    ["one", "two", "three"]
  end
end

# /spec/interactions/test_array_spec.rb
RSpec.describe TestArray, type: :interaction do
  let(:outcome) { described_class.run }
  let(:result) { outcome.result }
  let(:errors) { outcome.errors }

  describe "#execute" do
    it "adds a random option to the responses array" do
      expect(outcome.options).to include(result.first)
    end

    it "initializes default on each run" do
      run_a = described_class.run
      expect(run_a.responses.length).to eq 1 #=> 2
      run_b = described_class.run
      expect(run_b.responses.length).to eq 1 #=> 3
    end
  end
end

```

**Comment by AaronLasseigne** [comment]
[Defaults](https://github.com/AaronLasseigne/active_interaction#defaults) are processed when the file is loaded. If you want it to be initialized each time put it in a lambda.

```ruby
array :responses, default: -> { [] }
```

**Comment by ScotterC** [comment]
🤦:)
Glad there’s already docs in place! I’ll go try reading them.

**Comment by ScotterC** [comment]
Coming back to this because I realized my mental model wasn't fully developed. To confirm:

In this test case, the responses array is assigned to memory on file load and future interaction runs are using the same reference to that responses array which is why the array length can increase across interactions. Is that correct?
