### ISSUE TITLE
Two datatypes with same variable name

### ISSUE THREAD

**Issue by umamaheswari-raj** [AaronLasseigne/active_interaction#571]
In my code, I have two types of edits: if the post already has a video, I receive only the link as a string in the edit part. If the post doesn't have a video, I send the video as a file. How do I handle this in the Active Interaction gem? I used the following, but I got the error "Video is not a valid file".

here is my code,

string :video, default: nil
file :video, default: nil

**Comment by AaronLasseigne** [comment]
It looks like you're doing it correctly. What is the Ruby class of the file you're sending to the interaction?

**Comment by antulik** [comment]
I would suggest to use different input names for string and file.
