### ISSUE TITLE
strange warning message

### ISSUE THREAD

**Issue by alec-c4** [AaronLasseigne/active_interaction#577]
Hey!
I see a strange warning message in my terminal `Also please contact the author of active_interaction-5.3.0 to request adding ostruct into its gemspec.` since I've updated to ruby 3.3.5

What's wrong?

**Comment by AaronLasseigne** [comment]
Looks like `ostruct` is being removed from the stdlib and this is a warning. I'll add it to the gemspec. Thanks!
